---
name: 'ci'
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'install go'
        uses: 'actions/setup-go@v2'
        with:
          go-version: '1.15'
      - name: 'checkout'
        uses: 'actions/checkout@v2'
      - name: 'build'
        run: "make build"
