name: 'bump & tag version'
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@master'
      - name: 'read VERSION.txt'
        id: 'read-version'
        uses: 'juliangruber/read-file-action@v1'
        with:
          path: './VERSION.txt'
      - name: 'bump version and push tag'
        uses: 'mathieudutour/github-tag-action@v4.6'
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          custom_tag: '0.0.2'
          # custom_tag: "${{ steps.read-version.outputs.content }}"
