---
name: 'pr'
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  yamllint:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'checkout'
        uses: 'actions/checkout@v2'
      - uses: './.github/actions/yamllint'

  hadolint:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'checkout'
        uses: 'actions/checkout@v2'
      - uses: './.github/actions/hadolint'
        with:
          args: |
            ./.github/actions/hadolint/Dockerfile \
            ./.github/actions/yamllint/Dockerfile \
            ./.github/actions/goss/Dockerfile

  build-linux:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'install go'
        uses: 'actions/setup-go@v2'
        with:
          go-version: '1.15'
      - name: 'checkout'
        uses: 'actions/checkout@v2'
      - name: 'build'
        run: 'make build-linux'
      - name: 'test'
        run: 'go test'

  build-raspberrypi:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'checkout'
        uses: 'actions/checkout@v2'
      - name: 'build'
        run: 'make build-raspi'
      - name: 'test'
        run: 'go test'
      - uses: 'actions/upload-artifact@master'
        with:
          name: 'one-wire-temp_raspi'
          path: './one-wire-temp_raspi'

  goss-raspberrypi:
    runs-on: 'raspberrypi'
    needs: 'build-raspberrypi'
    steps:
      - name: 'checkout'
        uses: 'actions/checkout@v2'
      - uses: 'actions/download-artifact@master'
        with:
          name: 'one-wire-temp_raspi'
          path: './one-wire-temp_raspi'
      - run: |
          chmod +x ./one-wire-temp_raspi && \
          ./one-wire-temp_raspi
      - uses: './.github/actions/goss'
        with:
          args: '-g goss.pi.yaml validate -f documentation'

  pi-misc:
    runs-on: 'raspberrypi'
    if: false
    steps:
      - name: 'basic info'
        run: |
          uptime
          hostname
          ip addr
          pwd
          ls -la
          whoami
