---
name: 'pr'
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  yamllint:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'checkout'
        uses: 'actions/checkout@v2'
      - uses: './.github/actions/yamllint'

  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'install go'
        uses: 'actions/setup-go@v2'
        with:
          go-version: '1.15'
      - name: 'checkout'
        uses: 'actions/checkout@v2'
      - name: 'build'
        run: 'make build-linux'
      - name: 'test'
        run: 'go test'

  pi:
    runs-on: 'raspberrypi'
    steps:
      - name: 'basic info'
        run: |
          uptime
          hostname
          ip addr
          pwd
          ls -la
          git status
